[tasks.clean]
description = "clean"
command = "rm"
args=["-f","nope.o","nope"]
[tasks.compile]
description = "build from obj"
script=['''
#!/usr/bin/env bash
gcc -o nope64 nope64.s
gcc -o nope86 nope86.s -m32
''']
[tasks.run]
description = "build and run"
script=['''
#!/usr/bin/env bash
./nope64
./nope86
''']
dependencies=["install"]